---
# https://ansible.readthedocs.io/projects/antsibull-docs/collection-docs/
name: Collection Docs
concurrency:
  group: docs-push-${{ github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    tags:
      - '*'
  # Run CI once per day (at 09:00 UTC)
  # schedule:
  #   - cron: '0 9 * * *'
  # Allow manual trigger (for newer antsibull-docs, sphinx-ansible-theme, ... versions)
  workflow_dispatch:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build docs
        shell: bash
        # https://ansible.readthedocs.io/projects/antsibull-docs/collection-docs/#building-a-docsite
        run: |
          pip install antsibull-docs sphinx_ansible_theme
          mkdir built-docs
          antsibull-docs sphinx-init --use-current --squash-hierarchy unbyte.gridscale --dest-dir built-docs
          cp .github/workflows/docs/conf.py built-docs/
          cp .github/workflows/docs/antsibull-docs.cfg built-docs/
          cat built-docs/antsibull-docs.cfg
          cd built-docs
          python -m pip install -r requirements.txt
          ansible-galaxy collection install ../ --force
          ./build.sh
      - name: Upload gh-pages docs as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: built-docs/build/html/

  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    # We don't push to gh-pages branch
    # In Pages settings "Source" must be set to "GitHub Actions"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'github-pages'
