---
name: tests
concurrency:
  # Limit the concurrency for a specific branch.
  group: tests-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sanity-tests:
    name: Run sanity tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ansible_collections/unbyte/gridscale
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run sanity tests
        shell: bash
        run: |
          cd ansible_collections/unbyte/gridscale
          ansible-test sanity --docker default --python 3.12
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ansible_collections/unbyte/gridscale
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run unit tests
        shell: bash
        run: |
          cd ansible_collections/unbyte/gridscale
          ansible-test units tests/unit/ --docker default --python 3.12
